ranks:
  cooldown: 60
  min: 5
  max: 10
  id: 0
bot:
  token: ''
  id: 0 # the id to use when syncing app commands
  extensions:
    - jishaku
    - utils.help
    - cogs.ranks
    - cogs.errors
    - cogs.management
    - cogs.owner
  allowed_mentions:
    roles: false
    everyone: false
    users: false
    replied_user: false
  config:
    command_prefix: ''
    owner_ids: []
    description: ''
  activity:
    type: ''
    text: ''
  logging:
    level: INFO
    format: '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
  database:
    host: postgres
    port: 5432
    user: postgres
    password: ''
