version: "3.9"
services:
    postgres:
        restart: unless-stopped
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - type: volumes
              source: bot-db
              target: /var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${pg_password}
    bot:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        command: ["./wait-for-it.sh", "postgres:5432", "--", "python", "bot.py"]
        env_file:
            - .env
volumes:
    bot-db: