version: "3.8"
services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
            interval: 3s 
            timeout: 5s
            retries: 5
        volumes:
            - type: volume
              source: bot-db
              target: /var/lib/postgresql/data
            - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
        env_file:
            - .env
    bot:
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
volumes:
    bot-db: null
