version: "3.8"
services:
    postgres:
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        build:
            context: ./db
            dockerfile: Dockerfile
        volumes:
            - type: volume
              source: bot-db
              target: /var/lib/postgresql/data
        env_file:
            - .env
    bot:
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
volumes:
    bot-db: null